threadpool:
  download_cores: 5
  denoise_cores: 3
  alpha_cores: 7
  fastqc_cores: 7
  import_cores: 5
  fastqdump_cores: 5
  taxonomy_cores: 3
  keep_alive_time: 10
spring:
  main:
    web-application-type: none
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
