threadpool:
  downloadCores: 5
  denoiseCores: 3
  alphaCores: 7
  fastqcCores: 7
  importCores: 5
  fastqdumpCores: 5
  taxonomyCores: 3
  keepAliveTime: 10
file:
  ALL_WORK_DIRECTORY: /data/test
  FILES: /data/test/files
  CLASSIFIER_PATH: /home/ssgss/下载/silva-138-99-nb-classifier.qza
  CSV_PATH: /data/test.csv
spring:
  main:
    web-application-type: none
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
