threadpool:
  downloadCores: 10
  denoiseCores: 7
  alphaCores: 5
  fastqcCores: 10
  importCores: 10
  fastqdumpCores: 10
  taxonomyCores: 7
  keepAliveTime: 20
file:
  ALL_WORK_DIRECTORY: /home/liangtian/ssgss/newdata
  FILES:
  CLASSIFIER_PATH: /home/liangtian/ssgss/silva-138-99-nb-classifier.qza
  CSV_PATH: /home/liangtian/ssgss/newdata/newdata.csv
spring:
  main:
    web-application-type: none
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
